language: node_js

node_js:
  - 4.6.1
  
install:
  - npm install
  
before_script:
  - sleep 15

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"